# Generated by Django 5.0.7 on 2024-07-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
