# Generated by Django 5.0.7 on 2024-07-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0002_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='count',
            new_name='count_city',
        ),
    ]
